### ISSUE TITLE
Throws error when `play_against_random=True`

### ISSUE THREAD

**Issue by reinismu** [Sandholm-Lab/ESCHER#1]
I set `play_against_random=True` and it throws an error

```
saved policy to  ./tmp/results//2022_09_19_15_00_12/policy_nodes_5748
saved policy to  ./tmp/results//2022_09_19_15_00_12/policy_nodes_5748full_model
Traceback (most recent call last):
  File "some-dir/ESCHER/ESCHER.py", line 1699, in <module>
    regret, pol_loss, convs, nodes = deep_cfr_solver.solve(save_path_convs=save_path)
  File "some-dir/ESCHER/ESCHER.py", line 985, in solve
    avg_reward = self.play_n_games_against_random(self._num_random_games)
  File "some-dir/ESCHER/ESCHER.py", line 864, in play_n_games_against_random
    reward = self.play_game_against_random()
  File "some-dir/ESCHER/ESCHER.py", line 848, in play_game_against_random
    probs = self._policy_network((obs, legal_actions_mask), training=False)
  File "some-dir/ESCHER/venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filenuraymor.py", line 34, in tf__call
    ag__.for_stmt(ag__.ld(self).hidden, None, loop_body, get_state, set_state, ('x',), {'iterate_names': 'layer'})
  File "/tmp/__autograph_generated_filenuraymor.py", line 31, in loop_body
    x = ag__.converted_call(ag__.ld(layer), (ag__.ld(x),), None, fscope)
ValueError: Exception encountered when calling layer "policy_network_1" "                 f"(type PolicyNetwork).

in user code:

    File "some-dir/ESCHER/ESCHER.py", line 308, in call  *
        x = layer(x)
    File "some-dir/ESCHER/venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "some-dir/ESCHER/venv/lib/python3.10/site-packages/keras/engine/input_spec.py", line 277, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "dense_30" is incompatible with the layer: expected axis -1 of input shape to have value 11, but received input with shape (1, 7)


Call arguments received by layer "policy_network_1" "                 f"(type PolicyNetwork):
  • inputs=('tf.Tensor(shape=(1, 7), dtype=float32)', 'tf.Tensor(shape=(2,), dtype=float32)')
```

**Comment by reinismu** [comment]
Figured it out ...


`obs = tf.constant(state.observation_tensor(), dtype=tf.float32)`
to
`obs = tf.constant(state.information_state_tensor(), dtype=tf.float32)`
